name: Discord Webhook

on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: discord-webhook
      uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
      env:
        URL: ${{ secrets.WEBHOOK_URL }}
      with:
        webhook_url: $"URL"
